[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
